cc_app_ui <- function() {
  shiny::fluidPage(
    title = "Clinic Capacity Planner — Interface Version",
    shiny::tags$head(shiny::tags$meta(name = "description", content = "Compare clinic opening hours using your existing Excel visit exports."),
      shiny::tags$link(rel = "stylesheet", type = "text/css", href = "planner.css")),
    shiny::tags$header(class = "app-header",
      shiny::tags$div(class = "brand", shiny::tags$span(class = "brand-mark", "CP"),
        shiny::tags$div(shiny::tags$strong("Clinic Capacity Planner"), shiny::tags$span(class = "brand-sub", "Interface Version"))),
      shiny::tags$span(class = "local-label", "Local workspace")),
    shiny::tags$div(class = "workspace",
      shiny::tags$aside(class = "setup-panel", `aria-label` = "Analysis setup",
        shiny::tags$h2("Load a reporting period"),
        shiny::radioButtons("mode", "Analysis mode", choices = c("Basic · visit exports" = "basic", "Full · visits + planning inputs" = "full"), selected = "basic"),
        shiny::fileInput("visits", "Excel visit exports", multiple = TRUE, accept = ".xlsx", buttonLabel = "Choose files", placeholder = "One or more .xlsx files"),
        shiny::tags$p(class = "field-note", "Use the same columns as the original Visit Analysis Tool."),
        shiny::dateInput("as_of", "Reporting period ends", value = Sys.Date() - 1, format = "yyyy-mm-dd"),
        shiny::selectInput("weeks", "Weeks in the current period", choices = c(4, 8, 12, 16, 26, 52), selected = 8),
        shiny::tags$details(shiny::tags$summary("Workbook options"),
          shiny::checkboxInput("protected", "Password-protected exports", value = TRUE),
          shiny::conditionalPanel("input.protected", shiny::passwordInput("password", "Shared workbook password"),
            shiny::tags$p(class = "field-note", "Protected import requires Windows desktop Excel.")),
          shiny::numericInput("sheet", "Worksheet number", value = 1, min = 1, step = 1),
          shiny::selectInput("date_order", "Text date convention", c("Month / day / year" = "mdy", "Day / month / year" = "dmy"))),
        shiny::conditionalPanel("input.mode === 'full'",
          shiny::fileInput("planning", "Full planning workbook (optional)", accept = ".xlsx"),
          shiny::tags$p(class = "field-note", "Load visits first to download a template with your clinic names and dates.")),
        shiny::actionButton("analyse", "Analyse my exports", class = "btn-primary action-wide"),
        shiny::tags$div(class = "demo-choice", shiny::tags$span("Try the controls first"),
          shiny::actionButton("demo", "Load fictional example", class = "action-wide")),
        shiny::uiOutput("load_status"),
        shiny::tags$p(class = "privacy-note", "Files are processed by R on this computer. Save downloaded reports in your approved hospital folder.")),
      shiny::tags$main(class = "analysis-panel",
        shiny::tags$div(class = "page-heading", shiny::tags$div(shiny::tags$p(class = "eyebrow", "SERVICE PLANNING"),
          shiny::tags$h1("What changes when the hours change?")), shiny::uiOutput("period_badge")),
        shiny::uiOutput("workspace_content"))))
}
